export const metadata = {
  title: 'tcgdex',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <script src="https://kit.fontawesome.com/60dc905cc5.js" crossOrigin="anonymous"></script>
        {children}
        </body>
    </html>
  )
}
